---
- name: Change interface configs
  hosts: my-host-group
  gather_facts: 'no'
  connection: local
  vars:
    provider:
      host: "{{ ansible_host }}"
      username: "myuser"
      password: "mypassword"
      authorize: 'yes'
      transport: eapi
      validate_certs: no
      timeout: 20
      use_ssl: True
    interfaces:
      - name: Ethernet1
        description: CLOUDBUILDERS
      - name: Ethernet3
        description: CLOUDBUILDERS
  tasks:
    - eos_config:
        src: interfaces.j2
        provider: "{{ provider }}"
